### ISSUE TITLE
Speed issue in track fits

### ISSUE THREAD

**Issue by sgreilich** [FNTD/R-package#19]
The routine(s) to obtain track properties is terribly sluggish! One culprit is the use of lm / predict that has too much overhead. However, even if this can is improved (by a factor of 50 using .lm.fit) other parts of the routine are still too slow. 

ENTIRE PART MAY BE MOVED TO JAVA.

**Comment by sgreilich** [comment]
After a number of changes (.lm.fit instead of lm etc., multi-id sets can now be processed) the actual fitting runs approx. 4x faster. HOWEVER, it runs much faster without parallelization than with. There must be some massive slow down when processing these fits on the cluster.

**Comment by neuholz** [comment]
should be solved, or?

**Comment by sgreilich** [comment]
Solved by proper use of data.table
