### ISSUE TITLE
Bug in xml import of FNTD options for 'save.path'

### ISSUE THREAD

**Issue by sgreilich** [FNTD/R-package#20]
Something funny: in contrast to all other options, save.path is set to "character(0)" when read from xml, although nothing obvious (like in the xml file) seems to be different. Did work for me until your commit, Alex. Could you check this, please?

**Comment by neuholz** [comment]
I will check it ;)

**Comment by neuholz** [comment]
- other options (n.x ,...) don't behave right as well -> xml doesn't overwrite defaults
- correct.saturation default is not loaded and results in error

**Comment by neuholz** [comment]
xml seems to have some mistakes, I'm on it to fix them...

**Comment by neuholz** [comment]
Fixed  "Bug in xml import of FNTD options for 'save.path' #20"

- "save.path" in XML 2 times defined
