### ISSUE TITLE
Cluster not working

### ISSUE THREAD

**Issue by neuholz** [FNTD/R-package#23]
if use.cluster = TRUE:

 error :
###########################
...tracking and linking...
...starting cluster (24 nodes)...
Error in unserialize(node$con) : error reading from connection
Called from: unserialize(node$con)

in line 197 (process track and link)
    tracks         <- SG.parallel.lapply( cl,
                                          1:nrow(df.meta),
                                          track.and.link,
                                          my.options,
                                          df.meta)

**Comment by sgreilich** [comment]
Speicher Problem. Es reicht inzwischen die eine Option am Anfang des Skript zu ändern.

Viele Grüße, Steffen

Sendt fra min iPhone

Den 21. feb. 2016 kl. 20.56 skrev neuholz <notifications@github.com<mailto:notifications@github.com>>:


if use.cluster = TRUE:

error :
###########################
...tracking and linking...
...starting cluster (24 nodes)...
Error in unserialize(node$con) : error reading from connection
Called from: unserialize(node$con)

in line 197 (process track and link)
tracks <- SG.parallel.lapply( cl,
1:nrow(df.meta),
track.and.link,
my.options,
df.meta)

**Comment by neuholz** [comment]
seems not to work with "IBCT.workflow.example.R" :/
