### ISSUE TITLE
sg8000 + TestImages run error

### ISSUE THREAD

**Issue by neuholz** [FNTD/R-package#28]
error:
```
At sample hm1103  
Error in `[.data.frame`(df.distribution.par, i, c("mu.1", "mu.2", "mu.3",  :    undefined columns selected

```

error must be in FNTD.distribution after line 32 somewhere here:

```
      res.stacks.straggling          <- FNTD.distribution(FNTD.results$data$df.tracks$id, 
                                                          FNTD.results$data$df.tracks$frame.no,
                                                          FNTD.results$data$df.tracks$sd.intensity,
                                                          FNTD.get.option(FNTD.results$options, "distribution.method"),
                                                          df.distribution.par = FNTD.results$data$df.meta)
      
    }
  }
  
  message("\n")
  return(list(ref.slice = list(df.dist    = res.ref.slice.intensity$df.dist,
                               dist.plots = res.ref.slice.intensity$dist.plots),
              stacks    = list(intensity  = list(df.dist    = res.stacks.intensity$df.dist,
                                                 dist.plots = res.stacks.intensity$dist.plots),
                               straggling = list(df.dist    = res.stacks.straggling$df.dist,
                                                 dist.plots = res.stacks.straggling$dist.plots))))
}
```

**Comment by sgreilich** [comment]
Cannot reproduce error?

**Comment by neuholz** [comment]
Merkwürdig. Habe den Ordner mit allen R-Paketen gelöscht und erneut Biuld and Reload gemacht, trz gleicher Fehler. Ich versuche mal das R-Package neu von GitHub zu installieren.

**Comment by neuholz** [comment]
error for TestImages: df.distribution.par$n.peaks seems to be missing...

in FNTD.distribution:
`Warning message:
In max(unique(df.distribution.par$n.peaks), na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
Error in sort(ncol(df.distribution.par) - seq(2, n * 2, 2)) : 
  error in evaluating the argument 'x' in selecting a method for function 'sort': Error in seq.default(2, n * 2, 2) : 'to' cannot be NA, NaN or infinite
Called from: sort(ncol(df.distribution.par) - seq(2, n * 2, 2))`

n is Null (created from df.distribution.par$n.peaks)
