### ISSUE TITLE
Java heap space error for stitched files

### ISSUE THREAD

**Issue by neuholz** [FNTD/R-package#29]
Seems like 
`    tracks         <- SG.parallel.lapply( cl,
                                          1:nrow(df.meta),
                                          track.and.link,
                                          my.options,
                                          df.meta)`

in FNTD.process.track.and.link doesn't handle files, that are stiched (not even 2 x 2 images).

error:
`CALCULATING TRACKSPOT PROPERTIES
Error in checkForRemoteErrors(val) : 
  7 nodes produced errors; first error: java.lang.OutOfMemoryError: Java heap space
In addition: Warning messages:
1: closing unused connection 9 (<-localhost:11958) 
2: closing unused connection 8 (<-localhost:11958) 
3: closing unused connection 7 (<-localhost:11958) 
4: closing unused connection 6 (<-localhost:11958) 
5: closing unused connection 5 (<-localhost:11958) 
6: closing unused connection 4 (<-localhost:11958) 
7: closing unused connection 3 (<-localhost:11958) 
Called from: checkForRemoteErrors(val)`

**Comment by neuholz** [comment]
had something to do with missing options in the xml files...

**Comment by sgreilich** [comment]
Hallo Alex,

Welche Optionen denn genau? Das ist ja ein guter Fund, denn da kommt man erstmal nicht drauf. Shirin hatte sich ja auch schon mal mit ähnlichen Sachen herumgeschlagen – vielleicht unter Details in die Hilfe eintragen für FNTDoptions.

Grüße aus (haha) Halle,

Steffen

**Comment by neuholz** [comment]
Hey über Halle wird nicht gelacht :P 

Ich hatte das heap space Problem bei einer 2 x 2 stitched tif Datei und bin nacheinander folgende Schritte durchgegangen:
- java options heap space vergrößert
- keine Bilder ausgeben
- Cluster false

und das alles hat auf dem Server nichts gebracht.
Auf meinem Windows PC habe ich das gleiche gemacht und es lief immer noch nicht. Deshalb hab ich meine XML durch sg8000.xml ersetzt und damit läuft es jetzt auf meinem PC (ohne cluster).
Ob es so auch auf dem Server läuft, muss ich noch testen.
Die Baustelle ist also noch da (aber tritt nur bei den gestitchten Bildern auf).

BG, Alex

**Comment by neuholz** [comment]
Die Änderungen waren (soweit ich mich richtig erinnern kann):
- reference.slice = "1"  statt 6
- distribution.method  = "mixtools"
- correction.background method = "After tracking" 

Also irgendwo in der XML muss der Fehler gelegen haben. Auf dem Server läuft es jetzt auch, nur dass der nicht mit 8GB heap auskommt (wie der PC), sondern lieber 32 GB haben will (sonst heap space errror).

**Comment by sgreilich** [comment]
Mh, komisch…
