### ISSUE TITLE
Merge of df.tracks and df.trackspots in correction of angle yields too large data frame

### ISSUE THREAD

**Issue by sgreilich** [FNTD/R-package#47]

**Comment by neuholz** [comment]
Is this a speed problem? I solved the error by adding the option "allow.cartesian=TRUE" in the merge command, so that there can be duplicated keys in the result data.table. Memory allocation can be a problem when you don't work on the server...

**Comment by sgreilich** [comment]
Fixed, duplicate entries cause merge.data.table to throw this error message
